### ISSUE TITLE
Publication of the OpenCPN manuals

### ISSUE THREAD

**Issue by Rasbats** [leamas/ocpn-manuals#2]
There are two strands to this.

1. HTML product from asciidoc needs to be made from a repository.
2. I am guessing that Alec would not want **leamas.github.io** to be available for users as the definitive manual. Product needs to be available on [opencpn.org](opencpn.org).

Dave has not offered to add a repo under OpenCPN/OpenCPN where the asciidoc material is held and HTML can be produced.

@rgleason : Has the dev-manual asciidoc and has the ability to make the HTML product for the dev-manual.
@Rasbats  : Has the plugins-manual asciidoc and also has the ability to make HTML.

@Rasbats : Understands the need for version management and is prepared to create managed HTML. Scripting help needed from @leamas  to automate the updating of material from the dev plugin manuals.

Sorry to return to this theme but ...

Could the way forward be that @rgleason creates the dev-manual product, @Rasbats  creates the plugins-manual product?

How do we get Rick's HTML into [opencpn.org](opencpn.org) to replace this?
[https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual)

A separate link would be needed for a plugins manual page and a directory for the material. Initially this would run in parallel with the users manual until a new user manual was produced or dokuwiki links updated.

Could an FTP process for moving the HTML be automated?

**Comment by leamas** [comment]
I can understand that Dave hesitates in the current situation. Truth is that we don't have anything which is stable enough to even be called a beta. This is both about the manual(s) and the processes.

I also agree the we shouldn't use out personal accounts for several reasons. 

One way forward could be that we created a new github user, say ocpn_manuals. That would give us a neutral point where we could merge results. The user could invite all of us as collaborators. When we are in a more stable state, we could start linking to it, and later perhaps move it to a separate projects under the opencpn umbrella. 

Thoughts?

**Comment by rgleason** [comment]
```
How do we get Rick's HTML into opencpn.org to replace this?
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual
```

We would need to convert Html ----> Dokuwiki and FTP that into the OpenCPN Manuals as one of the "books".
Which is possible, but it might be easiest to have a separate opencpn.org/dev folder for HTML.  All editting needs to be done in asciidoc/antora to keep the process clean.

Plugin documentation similar?

**Comment by rgleason** [comment]
Alec's manual has some changes to the outline and it may be more current.

**Comment by leamas** [comment]
>    Product needs to be available on opencpn.org.

Yes and no. A link might be sufficient. If we create a separate user (see above) this will have Github Pages (GP) available which can be used.  Actually, since there is only in instance of GP per user, this might be a better option than a project under OpenCPN.

@all: Please DONT RUSH AWAY and create users etc. We need to discuss this first.

**Comment by Rasbats** [comment]
> User Manual for "Plugins" (DW) to Rasbats Plugins Manual (GP)

Rick ... I think you might have misunderstood. 

>  a new github user, say ocpn_manuals.

It would be this account that made the HTML content, not mine (or yours?). It would also be the account with the GP, avoiding the use of a personal account for publishing. I would still prefer new ocpn_manuals to have separate repos for dev-manual, plugins-manual and pull it together with a master ocpn_manuals repo (how would the links work???). Reason - I want to be able to test my product independently of the combined manual and avoid the current mess in the Rasbats repos.

**Comment by leamas** [comment]
> I would still prefer new ocpn_manuals to have separate repos for dev-manual, plugins-manual and pull it together with a master ocpn_manuals repo

So do I, actually

**Comment by leamas** [comment]
@rasbats: While you explain what I mean (thanks!), can I take your input as a separate user is a viable idea?

**Comment by leamas** [comment]
> I agree with Alec, about simple "links" from the Dokuwiki (DW) pages to Github Pages (GP)

What we really need is a formal blessing i. e., a link from opencpn.org. But we are not ready for that.

>  wonder if github will support use of GP for public use because of something that Rasbats wrote.
Are we likely to have problems if there is too much activity and traffic?

If we have a manual so popular that the traffic is a problem I'm sure we can publish the html somewhere else... let's kick this can down the road.

**Comment by leamas** [comment]
So, my proposal: let's create a new account at github.

  - Name like opencpn_manuals or so
  - Three projects: development manual, plugin manual and  master manual
  - All of us  (Mike, Rick. me) are administrators.

Agreed?

**Comment by leamas** [comment]
@Rasbats  @rgleason : ^

**Comment by Rasbats** [comment]
> can I take your input as a separate user is a viable idea?

Yes.

>  Name like opencpn_manuals or so
    Three projects: development manual, plugin manual and master manual
    All of us (Mike, Rick. me) are administrators.

Agree ... I prefer opencpn_manuals to ocpn.... 

> plugin manual 

Nitpicking 'plugins_manual'!

**Comment by leamas** [comment]
@rgleason @Rasbats : You should have invitations pending. We will need to clone current sources into the new projects, I have filed bugs for that but nothing more.

**Comment by rgleason** [comment]
Alec have accepted. May have a chance to focus on this in 2 days.

**Comment by leamas** [comment]
I got it wrong. In order for all of us to have full access opencpn-manuals needs to be an organization.I have converted it and sent new invitations.  When you accept those you are owners. As I  understand it, we have all the same privileges then (?)

**Comment by leamas** [comment]
All settled in the new opencpn-manuals user and projects. Closing
